name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # You can change this to your desired Java version
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml # You can add any additional Maven commands here
